package:
  name: floodestimation
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.0')[1:] }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  
source:
  git_url: ..

requirements:
  build:
    - python
    - setuptools
    - appdirs 1.4*
    - sqlalchemy 1.0*
    - numpy 1.9*
    - scipy >=0.16
    - lmoments3 >=1.0.2

  run:
    - python
    - appdirs 1.4*
    - sqlalchemy 1.0*
    - numpy 1.9*
    - scipy >=0.16
    - lmoments3 >=1.0.2

test:
  # Python imports
  imports:
    - floodestimation

about:
  home: http://github.com/OpenHydrology/floodestimation
  license: GPLv3
  licence_file: LICENSE
  summary: Python library for flood frequency-magnitude analyses for UK catchments
  readme: README.md

